In [1]:
import glob

import numpy as np
import pandas as pd

path = './data'
csv_files = glob.glob(path + '/*.csv')

df_list = (pd.read_csv(file) for file in csv_files)

df = pd.concat(df_list, ignore_index=True)

In [2]:
df.describe()

              Year  Winner Seed  Winner Score   Loser Seed  Loser Score
count  1133.000000  1133.000000   1133.000000  1133.000000  1133.000000
mean   2014.716681     4.945278     75.484554     8.601942    63.586937
std       5.497193     3.745976     10.697205     4.566303    10.241461
min    2006.000000     1.000000     47.000000     1.000000    29.000000
25%    2010.000000     2.000000     68.000000     5.000000    57.000000
50%    2014.000000     4.000000     75.000000     9.000000    63.000000
75%    2019.000000     7.000000     82.000000    13.000000    71.000000
max    2024.000000    16.000000    121.000000    16.000000   100.000000

In [3]:
df

,Year,Round,Winner Seed,Winner Name,Winner Score,Loser Seed,Loser Name,Loser Score
0,2006,first_round,1,UConn,72,16,Albany,59
1,2006,first_round,8,Kentucky,69,9,UAB,64
2,2006,first_round,5,Washington,75,12,Utah State,61
3,2006,first_round,4,Illinois,78,13,Air Force,69
4,2006,first_round,11,George Mason,75,6,Michigan State,65
...,...,...,...,...,...,...,...,...
1128,2024,elite_eight,11,NC State,76,4,Duke,64
1129,2024,elite_eight,1,Purdue,72,2,Tennessee,66
1130,2024,final_four,1,UConn,86,4,Alabama,72
1131,2024,final_four,1,Purdue,63,11,NC State,50
1132,2024,championship,1,UConn,75,1,Purdue,60

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1133 entries, 0 to 1132
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          1133 non-null   int64
 1   Round         1133 non-null   object
 2   Winner Seed   1133 non-null   int64
 3   Winner Name   1133 non-null   object
 4   Winner Score  1133 non-null   int64
 5   Loser Seed    1133 non-null   int64
 6   Loser Name    1133 non-null   object
 7   Loser Score   1133 non-null   int64
dtypes: int64(5), object(3)
memory usage: 70.9+ KB

In [5]:
first_round_games   = df.loc[df['Round'] == 'first_round']
second_round_games  = df.loc[df['Round'] == 'second_round']
sweet_16_games      = df.loc[df['Round'] == 'sweet_16']
elite_eight_games   = df.loc[df['Round'] == 'elite_eight']
final_four_games    = df.loc[df['Round'] == 'final_four']
champoinship_games  = df.loc[df['Round'] == 'championship']
champoinship_games

,Year,Round,Winner Seed,Winner Name,Winner Score,Loser Seed,Loser Name,Loser Score
62,2006,championship,3,Florida,73,2,UCLA,57
125,2007,championship,1,Florida,84,1,Ohio State,75
188,2008,championship,1,Kansas,75,1,Memphis,68
251,2009,championship,1,North Carolina,89,2,Michigan State,72
314,2010,championship,1,Duke,61,5,Butler,59
377,2011,championship,3,UConn,53,8,Butler,41
440,2012,championship,1,Kentucky,67,2,Kansas,59
503,2013,championship,1,Louisville,82,4,Michigan,76
566,2014,championship,7,UConn,60,8,Kentucky,54
629,2015,championship,1,Duke,68,1,Wisconsin,63
692,2016,championship,2,Villanova,77,1,North Carolina,74
755,2017,championship,1,North Carolina,71,1,Gonzaga,65
818,2018,championship,1,Villanova,79,3,Michigan,62
881,2019,championship,1,Virginia,85,3,Texas Tech,77
943,2021,championship,1,Baylor,86,1,Gonzaga,70
1006,2022,championship,1,Kansas,72,8,N. Carolina,69
1069,2023,championship,4,UConn,76,5,San Diego St.,59
1132,2024,championship,1,UConn,75,1,Purdue,60

In [6]:
champoinship_games.mode()

,Year,Round,Winner Seed,Winner Name,Winner Score,Loser Seed,Loser Name,Loser Score
0,2006,championship,1.0,UConn,75.0,1.0,Butler,59.0
1,2007,NaN,NaN,NaN,NaN,NaN,Gonzaga,NaN
2,2008,NaN,NaN,NaN,NaN,NaN,Michigan,NaN
3,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
first_round_games['Winner Seed'].value_counts()

1     66
2     61
3     59
4     53
5     41
7     41
6     35
8     34
9     34
11    33
12    27
10    26
13    15
14     9
15     7
16     2
Name: Winner Seed, dtype: int64

In [8]:
second_round_games['Winner Seed'].value_counts()

1     61
2     47
3     44
4     37
5     27
11    18
7     18
6     14
8      9
12     8
10     7
9      6
13     4
15     4
Name: Winner Seed, dtype: int64

In [9]:
sweet_16_games['Winner Seed'].value_counts()

1     45
2     31
3     21
4     12
11     7
5      7
6      5
7      4
9      4
10     3
8      3
12     1
15     1
Name: Winner Seed, dtype: int64

In [10]:
elite_eight_games['Winner Seed'].value_counts()

1     26
2     14
4      7
3      6
11     5
5      5
8      3
7      3
9      2
10     1
Name: Winner Seed, dtype: int64

In [11]:
final_four_games['Winner Seed'].value_counts()

1    20
2     4
3     4
8     3
5     2
4     2
7     1
Name: Winner Seed, dtype: int64

In [12]:
champoinship_games['Winner Seed'].value_counts()

1    13
3     2
7     1
2     1
4     1
Name: Winner Seed, dtype: int64

In [13]:
champoinship_games.describe()

              Year  Winner Seed  Winner Score  Loser Seed  Loser Score
count    18.000000    18.000000     18.000000   18.000000    18.000000
mean   2014.722222     1.777778     74.055556    3.166667    64.444444
std       5.654832     1.592466      9.698224    2.595245     9.224151
min    2006.000000     1.000000     53.000000    1.000000    41.000000
25%    2010.250000     1.000000     68.750000    1.000000    59.000000
50%    2014.500000     1.000000     75.000000    2.000000    64.000000
75%    2018.750000     1.750000     81.250000    4.750000    71.500000
max    2024.000000     7.000000     89.000000    8.000000    77.000000